name: built_html_example
version: 1.0.0
description: Example to build *.html, *json files from *.template.html and *.template.json source.

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0
  built_html:
    path: ../
