name: built_html
version: 0.1.3
author: Jacob MacDonald <jakemac53@gmail.com>
description: A Builder for injecting content hashes into html templates
homepage: https://github.com/jakemac53/built_html

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: ^1.0.0
  yaml: ^2.1.15

dev_dependencies:
  build_test: ^0.10.0
  test: ^1.5.0
